### PR TITLE
Modifies SIGHASHER variable as specified in #128

### PR DESCRIPTION
**Pull request by hahnmichaelf**
Fixes issue #128 

As discussed in gitter, change to naming for sighash/sighasher to make it clearer to understand.

Changes for ease of understanding:
-File _sighash.se.py_ to _msg_hash.se.py_
-Adds a comment at variable declaration for MSG_HASHER.

-`SIGHASHER` to `MSG_HASHER`
-`SIG_HASHER_TX_HEX` to `MSG_HASHER_TX_HEX`
-`SIGHASHER_GAS_LIMIT` to `MSG_HASHER_GAS_LIMIT`
-`sighasher` to `msg_hasher`
-`sighash` to `msg_hash`
-`sig_hasher_address` to `msg_hasher_address`
-`sig_hasher_tx` to `msg_hasher_tx`
-`sighash_1` to `msg_hash_1`
-`sighash_2` to `msg_hash_2`
-`test_sig_hasher_is_pure` to `test_msg_hasher_is_pure`

### CODE REVIEW

**Comment by djrtwo** [comment]
Thanks! Can you fix the build? Looks like you need to update things related to this name change in testing

**Comment by hahnmichaelf** [comment]
@djrtwo Should be good to go now.

**Comment by paulhauner** [comment]
FYI @hahnmichaelf, I just came across a bunch of references to `sighash` in https://github.com/ethereum/casper/tree/master/tests :smile:

**Comment by hahnmichaelf** [comment]
@paulhauner There are a lot of references to `sighash` in _conftest.py_ as well as in _sighash.se.py_. Not to mention the name itself. I am unsure as to whether or not that's what @djrtwo was referring to when he created the issue. If it is, I can try to change all potential instances of `sighash` as well.

**Comment by djrtwo** [comment]
Good call @paulhauner. We should definitely change var names that reference a `sighash` to reference a `msg_hash` now. There will be vars like this throughout the contract and testing. Also should change the filename of the sighash source. 

My fault @hahnmichaelf for leaving this out in the issue. Thanks again for the help!

**Comment by djrtwo** [comment]
LGTM!
Thanks :)

**Pull request merged**
