### PR TITLE
Updates to run daemon with python 3

### PR DESCRIPTION
**Pull request by hstove**
Hopefully this helps with #2 . I haven't fully ran the daemon with a node, but these code updates at least let you get past the errors to start running the app.

With `accounts.py`, I saw the comment on the top that mentioned it was copied from `pyethapp`. I just went to that file, grabbed the latest version, and pasted it in there. It seems to work.

Thanks again Ethereum team for simply everything!

### CODE REVIEW

**Comment by djrtwo** [comment]
Are we still doing dev on /daemon?
If not, close this PR.

@karlfloersch @ChihChengLiang

**Comment by hstove** [comment]
I am a bit confused on the status of the FFG daemon development. I have done further work to clean up and run the daemon (not included here), and it appears that most of the daemon code has not been updated for the newer version of the contract. I may be mistaken, and this development may be happening elsewhere. I'd be happy to help in whatever way I can.

**Comment by djrtwo** [comment]
Pretty sure validator_service.py has overtaken it.
https://github.com/karlfloersch/pyethapp/blob/dev_env/pyethapp/validator_service.py

**Comment by hstove** [comment]
That makes plenty of sense. I'll close this, then.

Thanks for the follow up

**Pull request closed without merging**
