### PR TITLE
README: update for standard readme compliance, including adding a LICENSE, plus a Gitter badge, etc.

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Oops, this is the right room https://gitter.im/ethereum/casper

**Comment by jamesray1** [comment]
Thanks, updated!

**Comment by jamesray1** [comment]
Ready for review!

**Comment by ChihChengLiang** [comment]
Thanks @jamesray1

**Comment by jamesray1** [comment]
You're welcome @ChihChengLiang!

**Pull request merged**
